### ISSUE TITLE
Issue adding Link after creating Team (MSGraph.Put)

### ISSUE THREAD

**Issue by patrickabel** [Puzzlepart/spfx-solutions#1]
I am having an issue where the **endPointInfo** object is being returned with an empty array immediately following the creation of the MS Teams. This is causing the quick-launch link creation to be bypassed due to the if-statement. 

@wobba have you encountered this? async/await logic is already in place on the MSGraph.Get/Put so I'm not sure what else can be done except polling/re-trying.

`public static async CreateTeam(graphHttpClient: GraphHttpClient, groupId: string, siteUrl: string) {
        console.log("Creating team");
        await MSGraph.Put(graphHttpClient, `beta/groups/${groupId}/team`, "{}");

        let endPointInfo = await MSGraph.Get(graphHttpClient, `beta/groups/${groupId}/endpoints`);
        console.log(endPointInfo);

        if (endPointInfo && endPointInfo.value) {
            let info = endPointInfo.value.find(element => { return element.providerName === 'Microsoft Teams'; });
            let currentWeb = new Web(siteUrl);
            await currentWeb.navigation.quicklaunch.add("Teams", info.uri);
            console.log("Adding teams link");
        }
    }`

@wobba thanks again for sharing this – it's a great pattern to follow for run-once spfx extensions to compliment a provisioning solution.

**Comment by wobba** [comment]
I think polling with a 200ms timeout might be the best approach here. I'll
modify the code to be more robust. Probably caching issue somewhere.

man. 12. feb. 2018 kl. 22:21 skrev patrickabel <notifications@github.com>:

**Comment by wobba** [comment]
Added the polling loop so we should be good :)

**Comment by patrickabel** [comment]
@wobba yep looks good!
![screenshot at feb 13 09-23-11](https://user-images.githubusercontent.com/1153976/36157553-a708f002-109f-11e8-866d-572d0eb64b83.png)
