### ISSUE TITLE
Npm i creates a few warnings, do I ignore?

### ISSUE THREAD

**Issue by westerdaled** [Puzzlepart/spfx-solutions#11]
Followed instructions as per the readme.  
BTW I am happy to update the project via the O365Cli  if this what is required.

`
npm i 
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\colors-d6dc8d0d\lib\system\supports-colors.js'                                               
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\node-sass-31e93abb\test\fixtures\invalid\index.scss'                                         
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\blockScopeAwareRuleWalker.d.ts'                          
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\blockScopeAwareRuleWalker.js'                            
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\index.d.ts'                                              
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\index.js'                                                
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\programAwareRuleWalker.d.ts'                             
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\programAwareRuleWalker.js'                               
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\ruleWalker.d.ts'                                         
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\ruleWalker.js'                                           
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\scopeAwareRuleWalker.d.ts'                               
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\scopeAwareRuleWalker.js'                                 
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\syntaxWalker.d.ts'                                       
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\syntaxWalker.js'                                         
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\walkContext.d.ts'                                        
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\walkContext.js'                                          
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\walker.d.ts'                                             
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\language\walker\walker.js'                                               
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\blockExclusion.d.ts'                                
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\blockExclusion.js'                                  
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\classExclusion.d.ts'                                
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\classExclusion.js'                                  
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusion.d.ts'                                     
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusion.js'                                       
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusionDescriptors.d.ts'                          
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusionDescriptors.js'                            
npm WARN tar ENOENT: no such file or directory, lstat 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics
\node_modules\.staging\node-sass-31e93abb\test\fixtures\sass-path\orange'                                          
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusionFactory.d.ts'                              
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\exclusionFactory.js'                                
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\tagExclusion.d.ts'                                  
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\tslint-8b0f78fc\lib\rules\completed-docs\tagExclusion.js'                                    
npm WARN tar ENOENT: no such file or directory, open 'D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\
node_modules\.staging\office-ui-fabric-react-57ce0cd7\lib\components\Coachmark\Coachmark.js'                       
npm ERR! code E404                                                                                                 `
[Upgrade-report Save as MD.txt](https://github.com/Puzzlepart/spfx-solutions/files/3626802/Upgrade-report.Save.as.MD.txt)

**Comment by tarjeieo** [comment]
Feel free to update to 1.9.1 👍

**Comment by westerdaled** [comment]
Ah I thought one of you would say that!  I have started some the edits after the summary are a bit vague so having fun guessing where I might put these properties.  Will keep you posted

**Comment by westerdaled** [comment]
Ok, I got this far. It involve following the upgrade file but a fair amount of googling and swearing, in order to resolve the dependencies. Not for the fainthearted IT Pro 🙄.

![Npm -i](https://user-images.githubusercontent.com/937208/65241090-a8ba0600-dada-11e9-8edc-1666986451aa.PNG)
![Gulp ship](https://user-images.githubusercontent.com/937208/65241201-e74fc080-dada-11e9-976d-05abfeaca08a.PNG)

Looking at [AC's blog post and Stefan's comments](andrewconnell.com/blog/sharepoint-framework-v1-8-0-what-s-in-the-latest-update-of-spfx#support-for-typescript) , I am thinking I need to delete the modules dir and package-lock.json . This is what I will be doing next after zipping up this source dir.

**Comment by westerdaled** [comment]
Made a couple of syntax changes GoogleAnalyticsApplicaitonCustomizer.ts

line 61
` if (trackerID) {
      if(trackerID.search("GTM-")) {`


Line 81 
`      } else if (trackerID.search("UA-")) {`

Looks like TS which I trying learn has changed syntax . Now down to this 

Build target: SHIP
[13:31:47] Using gulpfile D:\Dev\Pnp\Puzzlepart\spfx-solutions\Pzl.Ext.GoogleAnalytics\gulpfile.js
[13:31:47] Starting 'default'...
[13:31:47] Starting gulp
[13:31:47] Starting subtask 'configure-sp-build-rig'...
value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
[13:31:52] Error - 'tsc' sub task errored after 3.28 s
 exited with code 2
[13:31:52] 'default' errored after 4.5 s

Any hints welcome because this giving me headache😫

**Comment by westerdaled** [comment]
taking a bit of advice from Bill Ayers, I started with a clean extension project and added over your code.  I take it I just need to wait to see whats up in GA . I don't need to enable anything in the Tenant WIde list ?

![Tenant wide deployment](https://user-images.githubusercontent.com/937208/65337360-e3e23500-dbbf-11e9-8c1c-a12f3702fa2c.PNG)

**Comment by westerdaled** [comment]
Just to confirm the following

I had to reverse the changes I made in GoogleAnalyticsApplicationCustomizerApplicationCustomizer.ts

so both Lines:  68 and 88 now have the original .startsWith method  as the search method generated 404 errors

`trackerID.startsWith`

I also need to add the "es6" directive  to tsconfig.json 

`lib": [
      "es5",
      "dom",
      "es2015.collection",
      "es6"
    ]
  },`

Now able view GA on my test tenant 😁.   This was an interesting learning experience.
