### ISSUE TITLE
Pzl.Ext.HighlightHome: How properly uninstall solution ?

### ISSUE THREAD

**Issue by 23W** [Puzzlepart/spfx-solutions#14]
Pzl.Ext.HighlightHome is good example how to connect Field Customizer with built-in field! But when solution is uninstalled from site, field still remains connected with nonexistent renderer and doesn't render correctly. Is it possible to correctly uninstall this solution ?

By the way. Is it possible to fallback to default renderer if field value is not processed (is not "Home" page doc icon)? Because for example we can easy add default icon for non-Home pages but, it's hard to find required doc icon for file item in Document List.

**Comment by wobba** [comment]
I'll take a look on uninstall actions if it's possible, or provide steps to unhook it.

And there is currently not a way to fallback afaik, which would be super useful indeed.

**Comment by 23W** [comment]
@wobba I think something like that:
```
await pnp.sp.web.lists.getById(list.Id).fields.getByInternalNameOrTitle('DocIcon').update({ ClientSideComponentId: '00000000-0000-0000-0000-000000000000' });
```
should remove connection. But where and how run it I don't know.

**Comment by wobba** [comment]
@23W I created a PR for this targeting the dev branch.
