### ISSUE TITLE
Is there away to debug SPFX extension?

### ISSUE THREAD

**Issue by mohammadamer** [Puzzlepart/spfx-solutions#17]
- [x] Question
I have implement this extension of "setting a group logo" it works in an environment but it's not working in another environment.
Can you help me how to debug such extension?

**Comment by olemp** [comment]
If you give us some debug information, then we could have a look.

**Comment by wobba** [comment]
See the offical documentation on extension debugging at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension#debug-your-application-customizer. That should help you out, setting breakpoints and stepping thru the code.

**Comment by mohammadamer** [comment]
Thanks!
I have a question - Regarding applying the following command
Apply-PnPProvisioningTemplate -Path template.xml -Parameters @{"LogoUrl"="https://contoso.sharepoint.com/SiteAssets/logo.jpg"}

Is there any way to check the LogoURL parameter value if it set correctly or not.
I mean if the extension is deployed to an environment by another person and I need to make sure that the extension is taking the right URL because currently the extension is deployed twice one as Prod and one as Test.
The test is working but Prod is not working
Could you help me figure out the issue.

**Comment by wobba** [comment]
Connect the site and run `Get-PnPCustomAction -Scope Site` and you can inspect the values of the custom action.

**Comment by mohammadamer** [comment]
Great! Thanks
Another more question.
MS Graph part. how to test it out site the code because it seems that this part is failing?
I mean this part
let graphClient: MSGraphClient = await this.context.msGraphClientFactory.getClient();
         
            let caller = await graphClient.api(graphUrl).version("v1.0").header("Content-Type", "image/jpeg").patch(buffer);


And about this part
   // Url wont propagate from exchange, so also setting it directly on group
            this.setGroupLogo(buffer);
We are not using it. should it work without it?

Thanks.

**Comment by wobba** [comment]
@mohammadamer  The solution is for setting a logo to a Group site. If it's a regular site (team site or communication site) you have to the the logo via the web object. It's a bit hard to figure out what your actual issue is without debugging, but that's outside the scope of this extension.

You may use it as is, or not :)
