### ISSUE TITLE
Text in Pzl.Part.CustomTextEditor is not searchable

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/spfx-solutions#20]
> Vi setter ikke header som searchableContent. Tipper det er ganske enkelt, kalle "setRteContentProp" med header informasjonen on update, og sørge for at den funksjonen bevarer content og header i forskjellige "containers" som ikke rører hverandre!

**Comment by olemp** [comment]
@tarjeieo Did you have a proposed solution here?

**Comment by wobba** [comment]
It should be looking at https://github.com/Puzzlepart/spfx-solutions/blob/ff947990f15fa471b8c72071d06a9af1ab5db8eb/Pzl.Part.CustomTextEditor/src/webparts/customTextEditor/CustomTextEditorWebPart.ts#L125 and https://github.com/Puzzlepart/spfx-solutions/blob/ff947990f15fa471b8c72071d06a9af1ab5db8eb/Pzl.Part.CustomTextEditor/src/webparts/customTextEditor/CustomTextEditorWebPart.ts#L53

If it's not indexed there might be a bug, and using maintenancemode=true you can check what content is actually stored and should be indexed.

**Comment by olemp** [comment]
> It should be looking at
> 
> https://github.com/Puzzlepart/spfx-solutions/blob/ff947990f15fa471b8c72071d06a9af1ab5db8eb/Pzl.Part.CustomTextEditor/src/webparts/customTextEditor/CustomTextEditorWebPart.ts#L125
> 
> and
> https://github.com/Puzzlepart/spfx-solutions/blob/ff947990f15fa471b8c72071d06a9af1ab5db8eb/Pzl.Part.CustomTextEditor/src/webparts/customTextEditor/CustomTextEditorWebPart.ts#L53
> 
> If it's not indexed there might be a bug, and using maintenancemode=true you can check what content is actually stored and should be indexed.

<3

**Comment by olemp** [comment]
> If it's not indexed there might be a bug, and using maintenancemode=true you can check what content is actually stored and should be indexed.

It seems like it's stored correctly:

```json
{
  "id": "b0b7a7d8-183b-4447-bdd3-246d84c67ee7",
  "instanceId": "9fe32ef7-2de8-42bf-9559-2ee2afcd1935",
  "title": "Tekst",
  "description": "Legg til og formater tekst",
  "serverProcessedContent": {
    "htmlStrings": {
      "searchableContent": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, nisi faucibus imperdiet volutpat, odio ante vulputate ligula, ut pellentesque est ante id mi. Vestibulum sem nisl, porta nec rhoncus et, aliquam at nisl. Donec turpis arcu, ornare et nulla in, efficitur fermentum urna. Nulla ut ultricies justo. Ut suscipit tincidunt erat quis lobortis. Proin vel scelerisque libero, in mollis sapien. Sed volutpat imperdiet arcu, ultrices lacinia libero dapibus sit amet. Nunc facilisis finibus augue, a scelerisque neque luctus a. Aenean condimentum, metus nec pretium imperdiet, lorem erat luctus lorem, sed dapibus sapien dui vehicula lorem. Proin ut sem efficitur, semper tellus et, tincidunt nisl. Phasellus quis imperdiet ante. Phasellus nibh risus, venenatis sollicitudin pharetra quis, hendrerit a quam. Nullam elementum magna scelerisque, efficitur elit quis, condimentum metus.</p>"
    },
    "searchablePlainTexts": {},
    "imageSources": {},
    "links": {}
  },
  "dataVersion": "1.0",
  "properties": {
    "description": "CustomTextEditor",
    "underlineLinks": true,
    "title": "Les dette før du leser videre",
    "Content": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, nisi faucibus imperdiet volutpat, odio ante vulputate ligula, ut pellentesque est ante id mi. Vestibulum sem nisl, porta nec rhoncus et, aliquam at nisl. Donec turpis arcu, ornare et nulla in, efficitur fermentum urna. Nulla ut ultricies justo. Ut suscipit tincidunt erat quis lobortis. Proin vel scelerisque libero, in mollis sapien. Sed volutpat imperdiet arcu, ultrices lacinia libero dapibus sit amet. Nunc facilisis finibus augue, a scelerisque neque luctus a. Aenean condimentum, metus nec pretium imperdiet, lorem erat luctus lorem, sed dapibus sapien dui vehicula lorem. Proin ut sem efficitur, semper tellus et, tincidunt nisl. Phasellus quis imperdiet ante. Phasellus nibh risus, venenatis sollicitudin pharetra quis, hendrerit a quam. Nullam elementum magna scelerisque, efficitur elit quis, condimentum metus.</p>",
    "textBoxStyle": 1
  }
}
```
