### ISSUE TITLE
PDF Resolve Images: RenderListAsStream

### ISSUE THREAD

**Issue by gbminnock** [Puzzlepart/spfx-solutions#6]
Question: 
I noted that html files in  document library can utilise this renderStreamAsList function to generate a PDF. It doesnt seem to work with images though. 

Are you aware of anything which can enable this for me?

tks

**Comment by wobba** [comment]
@gbminnock As long as the images are referenced externally I think print to pdf is the closest you get unless you use some external component. If you have the image inline as a data URI it should work - as this post from John Liu shows - http://johnliu.net/blog/2017/10/generate-any-pdf-documents-from-html-with-flow

**Comment by gbminnock** [comment]
@wobba thanks
