### ISSUE TITLE
html conversion

### ISSUE THREAD

**Issue by johnnyshield** [Puzzlepart/spfx-solutions#8]
Hi - nice solution! The previous issue mentions html conversion, but this is not included on the list of acceptable file types. Is there a reason why this is excluded? Thanks

**Comment by wobba** [comment]
@johnnyshield it support the file types listed on the Microsoft Graph doc page. See https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0

**Comment by johnnyshield** [comment]
Thanks for the explanation
